server:
  port: 8080

spring:
  application:
    name: analog_equipment
  datasource:
    url: jdbc:mysql://localhost:3306/system_23?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSl=true&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  type-aliases-package: com.example.**.dao


#????
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

